apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubble.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: hubble-ui
          port: 80
