apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-manager-tetragon
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: tetragon.rules
      rules:
        - alert: TetragonSecurityPolicyTriggered
          expr: sum(increase(tetragon_policyfilter_operations_total[1m])) by (policy) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: "Tetragon Security Event: {{ $labels.policy }}"
            description: "The policy '{{ $labels.policy }}' was triggered on node {{ $labels.instance }}."
