apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: npm-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`npm.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: npm
          port: 81
          scheme: http
