apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  labels:
    app: searxng
data:
  settings.yml: |
    use_default_settings: true

    server:
      secret_key: "change_this_to_a_random_string"
      
    search:
      formats:
        - html
        - json
