apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
      version: "6.46.0"
  values:
    # Deployment mode: SingleBinary (simple), SimpleScalable (medium), Distributed (large)
    deploymentMode: SingleBinary

    # Number of replicas
    singleBinary:
      replicas: 1

    # Component replicas
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0

    # Caching
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false

    # Helm test
    test:
      enabled: false

    # All loki settings combined under one key
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          directory: /var/loki/chunks
      useTestSchema: true
