apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
      version: "6.46.0"
  values:
    deploymentMode: "SingleBinary"

    loki:
      storage:
        type: "filesystem"

      boltdbShipper:
        sharedStore: ""
