apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshots
spec:
  cron: "0 5 * * *" # 12:00 AM CDT
  task: "snapshot"
  groups:
    - backups
  retain: 5
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-backups
spec:
  cron: "0 6 * * SUN" # 1:00 AM CDT Sunday
  task: "backup"
  groups:
    - backups
  retain: 10
  concurrency: 1
