apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      version: "1.12.0"
  values:
    defaultSettings:
      backupTarget: "nfs://192.168.4.110:/mnt/pool-1/kubernetes"
      backupTargetCredentialSecret: ""

    longhornUI:
      replicas: 1
