apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "81.6.9"
  values:
    kubeProxy:
      enabled: false

    defaultRules:
      rules:
        kubeProxy: false

    grafana:
      admin:
        existingSecret: "grafana-admin-credentials"
        userKey: admin_user
        passwordKey: admin_password
      # It's best practice to null out the plaintext values to ensure they are not used.
      adminUser: ""
      adminPassword: ""

      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: false

    prometheus:
      prometheusSpec:
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelectorNilUsesHelmValues: false

        retention: 7d
        retentionSize: "80GB"

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 100Gi

        additionalScrapeConfigs:
          - job_name: "has-exporter"
            static_configs:
              - targets: ["192.168.4.52:9100"]
          - job_name: "proxmox-exporter"
            static_configs:
              - targets: ["192.168.4.73:9100"]
          - job_name: "proxmox-ve-exporter"
            metrics_path: /pve
            params:
              target: ["192.168.4.73"]
            static_configs:
              - targets: ["exporter-proxmox.monitoring.svc.cluster.local:9221"]
          - job_name: "unpoller"
            static_configs:
              - targets: ["unpoller.monitoring.svc.cluster.local:9130"]
          - job_name: "pihole-exporter"
            metrics_path: /metrics
            static_configs:
              - targets: ["pihole-dns.pihole.svc:9617"]

    alertmanager:
      alertmanagerSpec:
        alertmanagerConfigMatcherStrategy:
          type: None
