apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  replicas: 2 # High availability: Flux will ensure 2 pods are always running
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: ghcr.io/jonahgcarpenter/portfolio/portfolio:v2.0.0-beta.2
          ports:
            - containerPort: 8080
          env:
            - name: LOKI_URL
              value: "http://loki.monitoring.svc.cluster.local:3100"

          # Security Flex: Enforcing Principle of Least Privilege
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000

          # Readiness/Liveness Probes for Kubernetes self-healing
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080

          # Mounting the ConfigMap as a directory of files
          volumeMounts:
            - name: content-volume
              mountPath: /app/data
              readOnly: true

      volumes:
        - name: content-volume
          configMap:
            name: portfolio-content
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-tunnel
  labels:
    app: portfolio-tunnel
spec:
  replicas: 0
  selector:
    matchLabels:
      app: portfolio-tunnel
  template:
    metadata:
      labels:
        app: portfolio-tunnel
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2026.2.0
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: portfolio-tunnel-credentials
                  key: TUNNEL_TOKEN
          # Security Flex: Locking down the tunnel pod
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 65532 # Standard non-root user for distroless images
