apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: portfolio-lockdown
spec:
  endpointSelector:
    matchLabels:
      app: portfolio
  ingress:
    # Allow external traffic (from your Cloudflare Tunnel/Ingress Controller)
    # to reach the Go web server on port 8080
    - fromEndpoints:
        - matchLabels:
            "app": "portfolio-tunnel"
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    # Allow DNS resolution (Required to find Loki's service name)
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "kube-system"
            "k8s-app": "kube-dns"
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

    # Allow communication ONLY to the Loki service in the monitoring namespace
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "monitoring"
      toPorts:
        - ports:
            - port: "3100"
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: portfolio-tunnel-lockdown
spec:
  endpointSelector:
    matchLabels:
      app: portfolio-tunnel
  egress:
    # Allow DNS resolution
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": "kube-system"
            "k8s-app": "kube-dns"
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

    # Allow outbound connection to Cloudflare's Edge Network
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "7844"
              protocol: TCP
            - port: "443"
              protocol: TCP

    # Allow routing traffic to the portfolio app
    - toEndpoints:
        - matchLabels:
            "app": "portfolio"
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
