---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: portfolio-tunnel-credentials
  namespace: portfolio
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBzFP8117ogGvjQ0Bm14TaNTwDGOdwxDbpKUvSrI9SkztjUEhps2h3JpeM428fNNZAAIFCHNXFF5eXhx5AgBqH1bO6jzwKBreJW4j2ch0stri59MDrTZWJCnl+3jSBZAfQRjO4IdXHz8wZ3LgMY7FutWTQq9lMM4ZEyh7wEhW76+D1cScIUqEdrLenT03THchf56GbPUprXCBVyjEUMsJqHzlV3HSdK7w3HJymZbTC0+r+v8ibPrhjfxfS9pC0CbYf7FB1E+IpZFtAkApXirotB65Tw0CYjUIIGmjd+ufnAlNy82WRYG5u2ZayN1gB3zJkDUx9axL1K9YXNbntdmNanhMZvu8qxQApNEbvzYnmjem+nI5/N1lQTtzKm1uIgTUlsqk4h2oylHWoZsaToUx95LgFsOtoYH9jf1udPX5VjHdRFyDvSyZoTBOUeHawgowtqLXcN7IEs78SkfGomar48UmVqlGRQdhbXkgjl4OogCixB14vmOwngT11vMyp1gWJ5F1X8b1RkNKMgiFGMqlYdGxJW9cO5LgTG3SUszHe1fxC5M9c0MJ1kZwi/x2WJExdIc4V0iyI5PDxzIjbv1Zj+8Yz90I3O+7O6B+zUEhACAql0plyW+No51cOXhIQRZASemx8cijO5dLpSUvkfwltIduDXIt5c7F/jhZLMrH21MKPLeLXZ3Hkb5nRQQKiCkz0k2TL9GmTTPm743cRUPtsPJQPm3kAxSj2QDy6PX1ctI9kmmw8cRh134LGA5EyBG8xj3d3QhmupX4OFo7x4XnkYXWpw9wE3q7z4HGY/1nwp66KiaJYe9CvhoeHPu8RbXilbkcqylOYH7933qTMkzob4aiWSUr2OyRCwZXxKpG0YlKyy1L+BSwbXeQXFWiMsBvXQ3cnoQ3cJG6gP1grFF64LHZ6u77LJkQZCCVWD0ApLxPCuxGD0/GLm
  template:
    metadata:
      name: portfolio-tunnel-credentials
      namespace: portfolio
