apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: unpoller
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: unpoller-image
  policy:
    semver:
      range: ">=2.21.0"
