apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  interval: 30m
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
