apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tetragon
spec:
  interval: 15m
  chart:
    spec:
      chart: tetragon
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      version: "1.6.0"
  values:
    extraHostPathMounts:
      - name: sys-kernel-tracing
        hostPath: /sys/kernel/tracing
        mountPath: /sys/kernel/tracing

    tetragon:
      prometheus:
        serviceMonitor:
          enabled: true

    tetragonOperator:
      prometheus:
        serviceMonitor:
          enabled: true
