{
 "title": "UniFi Clients",
 "description": "UniFi Poller v2.0.1 Displays detailed information for clients in a UniFi network using Prometheus.",
 "tags": [
  "unifi",
  "unifi-poller"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_device_info{type=\"uap\"},source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_device_info{type=\"uap\",source=~\"$Controller\"},site_name)"
   },
   {
    "name": "AP",
    "query": "label_values(unpoller_device_info{type=\"uap\",site_name=~\"$Site\"},name)"
   },
   {
    "name": "Switch",
    "query": "label_values(unpoller_device_info{type=\"usw\",site_name=~\"$Site\"},name)"
   },
   {
    "name": "Wireless",
    "query": "label_values(unpoller_client_info{site_name=~\"$Site\", ap_name=~\"$AP\", wired!=\"true\"},name)"
   },
   {
    "name": "Wired",
    "query": "label_values(unpoller_client_info{site_name=~\"$Site\", sw_name=~\"$Switch\", wired=\"true\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" },
   { "name": "Identifier", "query": "name, name\\,mac" }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    }
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_uptime_seconds{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_receive_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_transmit_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (hostname) (unpoller_client_info{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (radio_proto) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (oui) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": " w {{oui}}"
    },
    {
     "expr": "count by (oui) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "e  {{oui}}"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "timeseries",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "timeseries",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Rx is on the negative axis. Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth / Apple Devices",
   "type": "timeseries",
   "description": "Apple Devices TX / RX bytes per second. Rx is on the negative axis. Tracks iPhones, iPads, Macs, Apple TVs, etc. If your Apple devices have different naming patterns, you can edit the query to use a different name pattern. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\".*[Ii][Pp]hone.*|.*[Ii][Pp]ad.*|.*[Mm]ac.*|.*[Aa]pple.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\".*[Ii][Pp]hone.*|.*[Ii][Pp]ad.*|.*[Mm]ac.*|.*[Aa]pple.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\".*[Ii][Pp]hone.*|.*[Ii][Pp]ad.*|.*[Mm]ac.*|.*[Aa]pple.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\".*[Ii][Pp]hone.*|.*[Ii][Pp]ad.*|.*[Mm]ac.*|.*[Aa]pple.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Cameras",
   "type": "timeseries",
   "description": "Cameras TX / RX bytes per second. Rx is on the negative axis. This graph shows any device with the word \"camera\" in its name and has nothing to do with UniFi Protect/video products. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{ap_name=~\"$AP\", name=~\".*[Cc]amera.*|.*[Cc]am.*\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{ap_name=~\"$AP\", name=~\".*[Cc]amera.*|.*[Cc]am.*\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{sw_name=~\"$Switch\", name=~\".*[Cc]amera.*|.*[Cc]am.*\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{sw_name=~\"$Switch\", name=~\".*[Cc]amera.*|.*[Cc]am.*\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_rssi_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_signal_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_noise_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "timeseries",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by ($Identifier) (rate(unpoller_client_wifi_attempts_transmit_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "timeseries",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_receive_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_retries_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_power_dbm{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_anomalies{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Satisfaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_satisfaction_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Roam Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_roam_count_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Connection Quality %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_ccq_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  }
 ]
}