apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 15m
  chart:
    spec:
      chart: unpoller
      sourceRef:
        kind: HelmRepository
        name: unpoller
        namespace: monitoring
      version: "2.11.2-Chart6"
  values:
    upConfig: |
      [poller]
          debug = false
          quiet = false
          plugins = []
      [prometheus]
        disable = false
        http_listen = "0.0.0.0:9130"
        report_errors = false
      [influxdb]
        disable = true
      [unifi]
          dynamic = false
      [loki]
          disable = true
      [[unifi.controller]]    
          url         = "https://192.168.4.1"
          user        = ""
          pass        = ""
          sites       = ["all"]
          save_ids    = true
          save_dpi    = true
          save_sites  = true
          hash_pii    = false
          verify_ssl  = false

    dashboards:
      create: false
      grafana:
        create: false
