apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgB6yWTroFw32guBllzdg2VaabGfCk6+hN8m9I58TzN9VAzxc3OaOIufWOyHHvuI7d3658uIotdMdL0mwSVIl7bKmUPxZA8VP8wova1NDkh10OmebWzJZlzpXEqIns11F7QfqEXuTik1s48OYC+QWn2XNUh/9tPM1EmIL7VCVNA3LND+Quvw7PCZW9D5wMchlfyVIQOoAIw+++7YxNeskSwiCE56O/0QOcDGpoyk+J2knnLwhr8vZ+wzz95RTbg7dW9D+XjYeBrx57dAL1oW/34OBTXVsIbvMWEp/Udb6Dg3b3ntjExMl7WFo2kH7dcVy/3SlRHmmXfZL794qE5i9LnG4ARHShVHRpizK1AHANH/TlM0P/su0ZTB1LKV7MvQDRs3MDwST8YpyYMuwtCiGZmnUNngS2AV1rzY4JUWJbIJnHgmjycwG2u1Yv7XEmTqA6WzKxSlov/hg7nqQAOB8v5fcU8tqG4J4zzTWETD9R9Wh+U02vNtpJ7K86J9G77QmVQ8tJnuVjO9LdIyzGWXMM4GwgOAKG4frSlGl261ip5EA4lIDhw5f602DkENpuLhTBr4XsUd0fMq8AaPNjxgkIx2iom5MbeVEwgpdscE6UnSirgDUxyN2wNHk7l63MtHlkBDrntVBYVf1F8zR0gKZidaxArLQHNiCikUVRkMO7jUh5cAAjVAWGd60iHR92vn+tlSqHeG3sN+h7vTaZx02N6VlgaHpv53vU02n2tdBt3DV1mX0Z1/9mSE7gbeNi/HIgTg9G+AtoPC6c4P9sCrjj5278DtGIdUJTLT/O/fjbUNVsLF52OLIkEHwPBKqU/EUQ4pPRi3lmedAhGrTV86J13FRvCK7W45OsrSkn3C+HhwGUNcrGzrwJLpEbKlCAYqP6Vx8H6rZWlHrKabWa2o1ZHKQaidrzsSSmF6tA26ovEIWzGnQLrYffSztIlv921NJd3sHwbuXAbRu4P5T2ra4Y4YjPZ1shMMdr5JkHxY7HVpnSnm+wmFxez35LpgC0AoCccM+z9aWtiImBC97mmdyj4OgIo4qNHmrvyEPkb2MHLC+o7sprcdmzXSWpFsxRvGzmZzIYBrcU0kIFcYI1BRmZd8M8agNAbZzbcJFlGapcwWUXZnkeT5rRt1gJ8FNJsv+eIpqko7iCU9G7A1pLBI7T96a00OnNoYPl1tdWOf0DQ7wwRG386WYBZWalihLUETGglxPbFg7MEuJNUcpfjIzpiV8RuT/wX8+wTwavePax4TTWy1Ixs7eOv0jOeAe1SAaBFhvZftPHrIWLFSceAbBQNTLD7EDAO7/ntxVyxJhbsSTxjr2Uim7C1vl3eaLA==
  template:
    metadata:
      name: unpoller-config
      namespace: monitoring
    type: Opaque
