---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgAvv8etGoBz+T4W5IZtB7QzJ4lK8DzafysxLJaoPbXdOKhRvya+8mS88avMgBN4bBpza3utBOHF084mYDLWKf3C4Hm2pDsJ1ezo56dNcCYcyFKOuLaS2xvf4MtA0RGN8YDC8lShMi43wVmojv+j5foaine3RLIZ8rNJ7rudYALlbprVtvkCJzjYEzaVhEF4b7n7g1CAE1K1/o80C10DZMFXpAqnhiQXdfCm8iu5FV2QwxQHsmGTAinZI6yGQ1/z4tq8piZPFB3xK61oE6XtfQBbZ1gx03MnH7mutv0Xmu3WVzI5j+go/LdbQmjgM3RGHfpeYbBQT17mIj8vYH3SfeVF2JntGhZav16Z715nhkKWScqg7nrbA1IxBauIpbtd31//wTRSuHTQirSvtbdApeLKYGmKjCj4s1hxyAbHITq9sCq772H1kpdUQ2yNOqV3ZRdFqQQ2mEJuOvxBePmiwjaA3Ji1WNWrEEGI0/HG552qldn2qFBJmsob0jwSMNuo5ykYkPEeO9WZ4mSQ4xxSKrGlDvTkHOgiZMoig9AC5ZJOOSV58wVWoXrIi703gM/6MRo/VOb66O9fdSpVCyWIa2dsm/PSd9DQaZOo0uX9gSp2GL3SL0fMxjzdgKrtPzaXVSMqdUqzhTRRCpQSVcq9V607XU0sK5/h1+26ReKwYJnqJP2E3p7K/k+BpIx+2M01D6F3heKV6+81Hu9ApI+OXl+cBklUif+p2jScCYA0qyzWQRF1u7xoMwVcNkinLbZQvpsHTtsrl83CqsKgtUMmSARib1oAoosMIkFdr/ADvQQt1BwgqOE+O6r9A2NgD4sx0JmqibwPPYPp0UnAKWvuJdMLrNPZmEdpQFBL3LK1BYUoTqVSEWiqwYfq9KEPVD4AMJrbHJGFAoZP3R+NGCj7kcOCf/MZHX4QoEhDR52/lI3Zfba5YPmoTG2l2M+wR7LQNreOvWahVyhmPByPD4M9jUXXecfvwrC3lQrbn0P9V/TcR7JmQwNEm0vwLCjWciK/BQxkT2PivYe69mWSfS3TKy2tsTfKiGKBY3xFBraR9WaIO4Hp4i+zHLNEwShtg1kMS77H4cxsxPT1zIsnhnYafYE1ITOwSkzVPjS/hqGafzT8emb+XjYuq09+9gVk6tPoa1myyoeKHK2cYbZyICDtULQhP0Kq1kmrV1ZnfZr2sp7meoQltEl1icMHGkkwItBpEGMzWL7TDgQwCMPOEGLVso2wrdOtPD5uPaStIA8cTjuyqkBdvZPJZmkhC3ZdJN5iMFWowBr5B5VzISf7Jxgx9So/XBjKpVaTocTBlfYzvESPzwJDhYN0RotkabCoHHXaP8NCM/8Qlkf4FUOfFT4+OH5KRQzxdWV12mAAuHvdSlp1pXLxBhOPQVK9DcQjxmM75ft3tQMaxGxJ/xC+hRFejfE2WToHxIB/MfeQ
  template:
    metadata:
      name: unpoller-config
      namespace: monitoring
    type: Opaque
