---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-config
  namespace: monitoring
spec:
  encryptedData:
    up.conf: AgAXtYiY+h+vwHSzsuUPZTn8pkQ4GBscYShst7nHo5/lP+YPzYcYO6hBBfcuihdkFvu2XAjNDuKLAsIof8JSvFCt1275KqD/gaZHyyAJITNjbXRpaHyr9fIwjgBsCs1mxUQq2Epr0UrvLry9O+7kxFDuFW6PYTbYVO0QSUjExmECAIXfuSGVhnUfMGUGgAkgUNvCcPUWpFL4Y9+HroILWvkxHT5J6uva5MB7ktxbeDmC4XwIRtdZKLxlqBi3xyxoAbNjU/fEIWGKUKqvu/JDddvkMpM75CfnD8S6D6OSPxw06qBX1YXtVllQvJQbkOmVVUxxcZreKWQ3xlLDEnE35asOEMarjcreDHvKGPgq7H3tgnbys88QXKwbCZXlbHzIzShz6IT+Ns+xOLKECptU3wsAqRE4UlxQZWGx1LHEqE382Bn1J12F4Ypvz9DPxCEnQRmjGIvXsB7r+ZmKbs4jgPXMsl1OcxytmvTikE77iHEAG69961wyjUHgBHearZCdUPt29Vr4esWSHIbQDtf31Ml1QHwPXzy3UojWM2C+DIeNwdSh+fA/OX7cPvdVJHh1lbUGR37XZEj9nv0QWsOTkP0YgMb99a2QMVF1K0CdyRkZZCoIdSkJMo+OudiGCkrd8tj5JZN9lWzfzynKT8ccHLX+DaHN5OLAV4AKHkmKI/ZyI6EYhZrAHu9F6wgQAOFMMDMmwtZwuHU5S8cw++dJhHnKozeiI/RIU+CpP/etnNbd3vr5zSWrDf7cOSluvFXuZQ4EzNv8M7siAvXrbign3W3xEbYDsVViT2gdh7fUjbv8K6d75Maa+0TXb2LQ4iT8gd9BrtP0RI1yD7Z0qTbrn0T7slanaNkTNqpxSmQDxhBZrLJwPzfFnm+K9ZADlNtytHb0ry4xY72OUui5xu5rpfrlbj0vDJmKV6ebS6SbKvFmN9YQpDLeX6UKgJ3Pl86fh2CkWaU/2nMzEPFYfIx1n8V9hq+Y0HD88fFu6xvB9eCbsv4saGvqOV3qjhlaJAERQPAjGj5L5vi/wZfXJJWrzTan7zIpjToUAl6ferfDhJEtr9SUGCbziZXIAHGayXBw8aJ5zNvF0XT/wOq5WYJwQTmnzIEzucEW5jH1Ay42a/G+F2xvz4Oneg48HEv3EUO4L3WBhwDm84qBGhGXb4gtImLSD4dktrYoJdcWBnNTk7/zbXLwjcg2FKHl/BEC17bcRh1FMWVzmhczprMsNyz58w1aUdYpFObAR3y21X3APUmo+4IunCalXgVzziyBiORsfqikaVwrlsPBMn6BCcXVWFkZDFDZRCd3EIlTVzVmaLR9oFSGVL3zQO60s1uhwxplPzHfeACeDsedpizFq5E218B/3R6PEsZngu3dwhAwE43eRJrGiV1JXAFouKnnYCFNWvmP3qQaS0Ln+eCbPdaAh6fdrk72lKdVw5fRng==
  template:
    metadata:
      name: unpoller-config
      namespace: monitoring
    type: Opaque
