apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpoller
spec:
  interval: 15m
  chart:
    spec:
      chart: unpoller
      sourceRef:
        kind: HelmRepository
        name: unpoller
        namespace: monitoring
      version: "2.11.2-Chart6"
  values:
    dashboards:
      create: false
      grafana:
        create: false
