apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homepage.home.jonahsserver.com`)
      kind: Rule
      services:
        - name: homepage
          port: 3000
