apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBYovjkbIzGG5uUwIzZqM0viz8+2V57FIS3PSoTmAMD1Vq9ecZKTUjsfQrRwU7N8Xpz+6nKYjQHwPuOh1dnIPxAva6Kq0zX+qYHjewLKJmz3mRaTLR1bhvEJ6B6ArTLC8Yf4t4XUzZ1w6WiIaGhiK7Ze33O3Xiu4iOOz2gdPmAu5xgfUIrXDQeXTymkP/JwzntMxn3a0mnE0mh9zY157mOPLedMACFpEuGXJ6FbEf+QgSePxahGyQ/+LaQCwp7WCdkMSUOFuRdVkApJVR6ravuL7acZEmcW3DLeTOT4V7JAS4l/f/wbuwUcdo/b2F2jS0pAFeOI8HTtHZP+F9pWWarUF4gAquFnQ+Gcsijw07A2Zb+iPg96hsNCr86eNFcXvY3GRGRW0/n5mD9FL7hHkfe6ClDTce/VleuNatFAp3r2KNxJb1e8oOJLLBc0cv3NFGWpgpK15jv0b3W5tjudCyyZp65xVyBo/V3JEUXRa2lXBvi460Kb5ZF0i5msulHDHnfcd+PLpQJ0hhWgAdIwHtbzdEGebB6tCuq7oIZfGoG4aKn2QLe4yZhjIEckmV1/zJLfffEaoHj2cv8xSOt17y79TETnEmt/5a4PVDvqw+zo8g5M+D622Edezpd9BtFxYvDn+hLvOiUcY/C4nNSpeRln3wd/t0ljcUjh7H/wfoag2/YN9243K0DCH+JG0I5UasTbrUZ+d267ExjfzlMu
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
    type: Opaque
