apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCCG7ju9C3gG48+ebBLkaEoPPrTP1l1EylqTSi91wmZdS3o7/C8FLUvbloRfQ93WkTt/qYdBjwTtzK0OO35KMb4N/gr29qVC0gGHaRX1517lknLWK22D+a9zETD9U+t5/ffQ6UZkUCzUastZ3vUOQ0chrCo8Rr2dESrLfvhN0wKq4HVkf6LrwC9fgNjWtmoanzB8AQ3APqKAcfZjByhOzWa/2lNhI70A58rE6Q3vMrTG4uPR5c/scMucGKt/Mvo8YJC7wQkBH7pNfkcUpH7SjMbfkaKK5DIoWaB4vSiwgqaW8qFLXdTU9b6VWoA37S/QcIZA5xH8uKfvo5eB2EuHHPYXLF/zQLDAz5afiWZdyuQ+uKdlQ4L0/h2eUjZh9CJ3abauhWN40s1x2r0NOVcPd3Njei6kAgKDGHrOey0iqQTTlcSZAkcRTuQ+aEN9g2Cnz9/Q8DWJk+FhJV1t3cDm1zfw1by4tY+NP4rKX9oRhqBkTyvienAxEtNapYVrgs7NE6UtP0rTbcUB/qCWzuW3HZAJdg4gyOGtq1nqnnFPpEZq6tcy88UWUwW1Nl3ktK6QVkUCmATeRPJ5D2GS7Bx6+MLm/obK4QCRsiNxcbJ5+EsDouj7FquErDB1hw7Yfm+tHD+9TM3fQq6g5rpDFjzZpy1Cm0oQOsYYv+inN+vZDvt4KdmMIfQXFJtdMz5kElbeOE2EUQSBZTgYoO0kZwq
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
    type: Opaque
