apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 15m
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "1.4.0"
  values:
    controller:
      type: "daemonset"

    alloy:
      configMap:
        content: |
          discovery.kubernetes "pod" {
            role = "pod"
            selectors = [
              {
                role  = "pod",
                field = "spec.nodeName=" + coalesce(sys.env("HOSTNAME"), constants.hostname),
              }
            ]
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pod.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              action        = "replace"
              target_label  = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              action        = "replace"
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              action        = "replace"
              target_label  = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
              action        = "replace"
              target_label  = "app"
            }
            rule {
              source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_container_name"]
              action        = "replace"
              target_label  = "job"
              separator     = "/"
              replacement   = "$1"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_id"]
              action        = "replace"
              target_label  = "container_runtime"
              regex         = "^(\\S+):\\/\\/.+$"
              replacement   = "$1"
            }
          }

          loki.source.kubernetes "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.process.pod_logs.receiver]
          }

          loki.process "pod_logs" {
            stage.static_labels {
              values = {
                cluster = "oswald-talos",
              }
            }
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
            }
          }
