apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "6.46.0"
  values:
    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: "longhorn"

    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0

    test:
      enabled: false

    lokiCanary:
      enabled: false

    loki:
      auth_enabled: false
      useTestSchema: true
      storage:
        type: filesystem
