apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bifrost
spec:
  interval: 15m
  chart:
    spec:
      chart: bifrost
      sourceRef:
        kind: HelmRepository
        name: bifrost
        namespace: bifrost
      version: "2.1.24"
  values:
    image:
      tag: "v1.5.15"

    bifrost:
      encryptionKeySecret:
        name: "bifrost-encryption-key"
        key: "encryption-key"
      providers:
        ollama:
          keys:
            - name: "Ollama"
              value: ""
              weight: 1
              models: ["*"]
              ollama_key_config:
                url: "http://192.168.4.106:11434"

      plugins:
        serviceMonitor:
          enabled: true
          interval: 30s
          scrapeTimeout: 10s
          namespace: monitoring

    storage:
      mode: sqlite
      persistence:
        enabled: true
        size: 10Gi
        storageClass: "longhorn"
      configStore:
        enabled: true
      logsStore:
        enabled: true

    postgresql:
      enabled: false

    vectorStore:
      enabled: false
      type: none
