apiVersion: v1
kind: ConfigMap
metadata:
  name: oswald-ai-config
data:
  LOG_LEVEL: debug
  SEARXNG_URL: "http://searxng:8080"
  OLLAMA_MODEL: "fredrezones55/Qwen3.5-Uncensored-HauhauCS-Aggressive:4b"
