apiVersion: v1
kind: ConfigMap
metadata:
  name: oswald-ai-config
data:
  OLLAMA_ROUTER_MODEL: "llama3.2:3b"
  OLLAMA_COMPLEX_MODEL: "llama2-uncensored:7b"
  OLLAMA_CODING_MODEL: "llama2-uncensored:7b"
  OLLAMA_UNCENSORED_MODEL: "llama2-uncensored:7b"
  OLLAMA_SIMPLE_MODEL: "llama2-uncensored:7b"
