apiVersion: apps/v1
kind: Deployment
metadata:
  name: oswald-ai
  labels:
    app: oswald-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oswald-ai
  template:
    metadata:
      labels:
        app: oswald-ai
    spec:
      # Block API token and kernel syscalls
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
        seccompProfile:
          type: RuntimeDefault

      initContainers:
        - name: init-storage
          image: ghcr.io/jonahgcarpenter/oswald-ai/oswald-ai:v2.3.0
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ ! -f /mnt/storage/soul.md ]; then
                cp /home/oswald-ai/config/soul.md /mnt/storage/soul.md
                echo "Seeded default soul.md into volume."
              fi
          volumeMounts:
            - name: storage-volume
              mountPath: /mnt/storage

      containers:
        - name: oswald-ai
          image: ghcr.io/jonahgcarpenter/oswald-ai/oswald-ai:v2.3.0

          # Enforcing Principle of Least Privilege
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL

          envFrom:
            - configMapRef:
                name: oswald-ai-config
            - secretRef:
                name: oswald-ai-secret

          # Mounting the storage directory
          volumeMounts:
            - name: storage-volume
              mountPath: /home/oswald-ai/config/soul.md
              subPath: soul.md
            - name: storage-volume
              mountPath: /home/oswald-ai/config/accounts
              subPath: accounts
            - name: storage-volume
              mountPath: /home/oswald-ai/config/memory
              subPath: memory

      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: oswald-ai-pvc
