apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-namespace-policy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 192.168.4.166/32
      ports:
        - protocol: TCP
          port: 5432
