apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aprilslilpugs-uploads-pvc
  namespace: aprilslilpugs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
