---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alp-web-tunnel-credentials
  namespace: aprilslilpugs
spec:
  encryptedData:
    TUNNEL_TOKEN: AgBMem1DPigexwkBqusZU9Qwn6BsOc2wmkwbow3i7uF03G4gqfuvx3VWhUXtDccbUEwhVYeDMb5DVFDRgThhVd1UhPqiJUF+03hnaJcycSA0vOEpkBpSyzmpP+Lj74YLQiFY/gxGRrHCFfwxnQDhqsjn/S8uCJ3/9WjyJoxFCpm7x914fkOTOs+DYtkOLvdaCYe8vHWBF3wdo98SQnmMxNvCt3OiLcAKJ2AV5Urvm0wLIm4vWP8105T/9OKk9JiqZCHioojBpx9jMLnquPgM/wNLt6+CumoOn3pONI3tadjPMc2J0Cn4h121uBdQNSEj9XQ+IFXodULqt/ihP0cSMoTPZUJNC2drqb5L45QCekfmWk2nsor8kBzuidALr9ykVVugk4hgzw+bbNAjPPGk55VRfJn0F0feA7G5+rwXwhzcxWNmS10wBDGtMVCwNvVdAQY7CisgjPmmhNtFhvwwQKLFI+NbuIAt0+NCmc53GKCR7c0JS8CFf5IxwBV/8yaYc3EbXgRToRTJzFuxoJErXdRythiW+8z3uWWoEd9bJU6sLxD+KqDah5HlmEN0uR5UKrLGOlFvyfslhEcb411+fCQybB08rf5o1EuY+okGNR4nuoGtSxdgEVic5VsUuEKwka5afcVVNk1r4fhQc82T18QOIrhaouLsRoC5hWBFwe6Pnf7+Khu2TuLiEd19KuRPiDkMEG0N7IcJPVR7ox4EonfnJTmcpdIxhgZbsRHqPxdct8cpLDLl+RzcYQml3KZRdZSHBa0tZ1rX6lrvoYro+o2LGM+sNvLnjol1HYc+BJzEa6H39ZYL4aCtTsRamOmzawf8ROPf09rCD1vGpsGf5AJAVnaCaUmXbTtODnmYeG+Wqovn9RJMkRG1y+c1K7hqMAHHAgYuZw+Z2jujDCAyYfiU7TvRv9qgYeMu+iVRKCvseUepznQD2DUz
  template:
    metadata:
      name: alp-web-tunnel-credentials
      namespace: aprilslilpugs
