apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper-tts
  labels:
    app: piper-tts
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: piper-tts
  template:
    metadata:
      labels:
        app: piper-tts
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: piper-tts
          image: lscr.io/linuxserver/piper:2.3.1
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 10200
          env:
            - name: PIPER_VOICE
              value: "en_US-c3po-medium"
            - name: TZ
              value: "Etc/UTC"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: OMP_NUM_THREADS
              value: "4"
          volumeMounts:
            - name: piper-config
              mountPath: /config
            - name: temp-data
              mountPath: /tmp
            - name: run-data
              mountPath: /run
      volumes:
        - name: piper-config
          persistentVolumeClaim:
            claimName: piper-pvc
        - name: temp-data
          emptyDir: {}
        - name: run-data
          emptyDir: {}
